(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let progress=null,selectedDeckSlot=0;
const screens={home:$('#screenHome'),cards:$('#screenCards'),deck:$('#screenDeck'),battle:$('#screenBattle'),profile:$('#screenProfile')};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function rarityClass(r){return ['common','rare','epic','legendary'].includes(r)?r:'common'}
function cardLevel(id){return Math.max(1,progress?.levels?.[id]||1)}
function updateWallet(){if(!progress)return;$('#trophyTop').textContent=progress.trophies;$('#goldTop').textContent=progress.gold;$('#gemsTop').textContent=progress.gems;$('#homeTrophy').textContent=progress.trophies}
function unlockedArena(){return [...GameConfig.arenas].reverse().find(a=>progress.trophies>=a.minTrophy)||GameConfig.arenas[0]}
function showScreen(name){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[name].classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='cards')renderCollection();if(name==='deck')renderDeck();if(name==='profile')renderProfile();if(name==='home')renderHome();if(name==='battle'){ArenaGame.start(progress.deck)}}
function renderHome(){const s=Auth.session(),a=unlockedArena();$('#homeName').textContent=s?.displayName||s?.username||'Player';$('#arenaName').textContent=a.name;$('#arenaList').innerHTML=GameConfig.arenas.map(x=>`<div class="arena-card ${progress.trophies<x.minTrophy?'locked':''}"><b>${esc(x.name)}</b><div class="muted">${progress.trophies>=x.minTrophy?'Terbuka':'🔒 '+x.minTrophy+' trophy'}</div></div>`).join('');$('#arenaProgressText').textContent=`${progress.trophies} trophy`;updateWallet()}
function statsText(c){if(c.type==='troop')return `${Math.round(c.damage||0)} DMG • ${Math.round(c.hp||0)} HP`;if(c.type==='spell')return `${Math.round(c.damage||c.heal||0)} power • ${c.radius||0} radius`;return `${Math.round(c.damage||0)} DMG • ${Math.round(c.hp||0)} HP`}
function cardHtml(c,extra=''){const lv=cardLevel(c.id);return `<div class="collection-card ${rarityClass(c.rarity)}" data-id="${c.id}" ${extra}><div class="cost">${c.cost}</div><div class="emoji">${c.emoji}</div><div class="rarity">${c.rarity} • ${c.type}</div><div class="name">${esc(c.name)}</div><div class="stats">${statsText(c)}</div><div class="level">Level ${lv}</div></div>`}
function renderCollection(){const f=$('#cardFilter').value;const list=CardDB.cards.filter(c=>f==='all'||c.type===f);$('#collectionGrid').innerHTML=list.map(c=>cardHtml(c)).join('');$('#collectionGrid').onclick=e=>{const el=e.target.closest('.collection-card');if(!el)return;upgradeCard(el.dataset.id)}}
function upgradeCard(id){const c=CardDB.byId(id);if(!c)return;const lv=cardLevel(id),max=GameConfig.economy.maxCardLevel;if(lv>=max){alert('Kartu sudah level maksimum');return}const cost=GameConfig.economy.upgradeBaseCost*lv;if(progress.gold<cost){alert(`Gold kurang. Butuh ${cost}`);return}progress.gold-=cost;progress.levels[id]=lv+1;Auth.saveProgress(progress);renderCollection();renderDeck();updateWallet()}
function renderDeck(){selectedDeckSlot=Math.min(selectedDeckSlot,7);$('#deckSlots').innerHTML=progress.deck.map((id,i)=>{const c=CardDB.byId(id);return `<button class="deck-slot ${i===selectedDeckSlot?'selected':''}" data-slot="${i}">${c?`${c.emoji}<br><b>${esc(c.name)}</b><br><small>Lv ${cardLevel(id)} • ${c.cost}⚡</small>`:'Kosong'}</button>`}).join('');$('#deckCollection').innerHTML=CardDB.cards.map(c=>cardHtml(c)).join('');const avg=progress.deck.map(id=>CardDB.byId(id)?.cost||0).reduce((a,b)=>a+b,0)/Math.max(1,progress.deck.length);$('#avgCost').textContent=`Rata-rata ⚡ ${avg.toFixed(1)}`;$('#deckSlots').onclick=e=>{const b=e.target.closest('[data-slot]');if(!b)return;selectedDeckSlot=Number(b.dataset.slot);renderDeck()};$('#deckCollection').onclick=e=>{const el=e.target.closest('.collection-card');if(!el)return;const id=el.dataset.id;if(progress.deck.includes(id)&&progress.deck[selectedDeckSlot]!==id){alert('Kartu itu sudah ada di deck');return}progress.deck[selectedDeckSlot]=id;Auth.saveProgress(progress);renderDeck()}}
function renderProfile(){const s=Auth.session();$('#profileName').textContent=s.displayName||s.username;$('#profileUsername').textContent='@'+s.username;$('#roleBadge').textContent=s.role==='owner'?'OWNER':'PLAYER';$('#winsStat').textContent=progress.wins;$('#lossStat').textContent=progress.losses;$('#cardsStat').textContent=CardDB.cards.length;const levels=Object.values(progress.levels||{});$('#levelStat').textContent=levels.length?(levels.reduce((a,b)=>a+b,0)/levels.length).toFixed(1):'1';$('#displayNameInput').value=s.displayName||s.username;$('#ownerPanel').classList.toggle('hidden',!Auth.isOwner());updateWallet()}
function enterApp(){const s=Auth.session();if(!s)return;progress=Auth.getProgress();$('#authScreen').classList.add('hidden');$('#gameShell').classList.remove('hidden');$('#versionLabel').textContent='v'+GameConfig.version;renderHome();showScreen('home')}
function leaveApp(){ArenaGame.stop();$('#gameShell').classList.add('hidden');$('#authScreen').classList.remove('hidden')}
function authMsg(text,ok=false){$('#authMessage').textContent=text;$('#authMessage').style.color=ok?'#92e6ad':'#ff9aa8'}
$('#showLogin').onclick=()=>{$('#showLogin').classList.add('active');$('#showRegister').classList.remove('active');$('#loginForm').classList.remove('hidden');$('#registerForm').classList.add('hidden');authMsg('')};
$('#showRegister').onclick=()=>{$('#showRegister').classList.add('active');$('#showLogin').classList.remove('active');$('#registerForm').classList.remove('hidden');$('#loginForm').classList.add('hidden');authMsg('')};
$('#loginForm').onsubmit=e=>{e.preventDefault();const r=Auth.login($('#loginUser').value,$('#loginPass').value);if(!r.ok)return authMsg(r.error);enterApp()};
$('#registerForm').onsubmit=e=>{e.preventDefault();const r=Auth.register($('#regUser').value,$('#regPass').value);if(!r.ok)return authMsg(r.error);enterApp()};
$$('[data-nav]').forEach(b=>b.onclick=()=>showScreen(b.dataset.nav));
$('#btnBattleBack').onclick=()=>{ArenaGame.stop();showScreen('home')};
$('#cardFilter').onchange=renderCollection;
$('#btnLogout').onclick=()=>{Auth.logout();progress=null;leaveApp()};
$('#profileForm').onsubmit=e=>{e.preventDefault();const r=Auth.updateProfile({displayName:$('#displayNameInput').value,password:$('#newPasswordInput').value});$('#newPasswordInput').value='';$('#profileNote').textContent=r.note||r.error||(r.ok?'Profil tersimpan':'');progress=Auth.getProgress();renderProfile();renderHome()};
window.addEventListener('arena:result',e=>{const d=e.detail,eco=GameConfig.economy;if(d.win){progress.wins++;progress.gold+=eco.winGold;progress.trophies+=eco.winTrophy}else{progress.losses++;progress.gold+=eco.loseGold;progress.trophies=Math.max(0,progress.trophies-eco.loseTrophy)}const a=unlockedArena();progress.selectedArena=a.id;Auth.saveProgress(progress);updateWallet();$('#resultIcon').textContent=d.win?'🏆':'💥';$('#resultTitle').textContent=d.win?'MENANG!':'KALAH';$('#resultText').textContent=d.win?`+${eco.winGold} gold • +${eco.winTrophy} trophy`:`+${eco.loseGold} gold • -${eco.loseTrophy} trophy`;$('#resultModal').classList.remove('hidden')});
$('#btnResultHome').onclick=()=>{$('#resultModal').classList.add('hidden');showScreen('home')};

// OWNER EDITOR
const modal=$('#editorModal'),list=$('#unitList'),form=$('#unitForm');let editId=null;
const fields=[['name','Nama','text'],['emoji','Emoji','text'],['cost','Cost Energi','number'],['hp','HP','number'],['damage','Damage','number'],['speed','Speed','number'],['range','Range','number'],['attackSpeed','Attack Cooldown','number'],['count','Jumlah Spawn','number'],['radius','Radius/Ukuran','number'],['splash','Splash','number'],['healAura','Heal Aura','number'],['duration','Duration','number'],['color','Warna','color']];
function renderEditorList(){list.innerHTML='';CardDB.cards.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='unit-row'+(editId===c.id?' active':'');b.innerHTML=`<span>${c.emoji}</span><span>${esc(c.name)}<br><small>${c.type} • ${c.rarity}</small></span>`;b.onclick=()=>selectEdit(c.id);list.appendChild(b)})}
function selectEdit(id){editId=id;const c=CardDB.byId(id);if(!c)return;form.innerHTML='';for(const [key,label,type] of fields){const val=c[key]??(type==='color'?'#ffffff':type==='text'?'':0);const div=document.createElement('div');div.className='field';div.innerHTML=`<label>${label}</label><input name="${key}" type="${type}" step="any" value="${esc(val)}">`;form.appendChild(div)}renderEditorList()}
$('#btnOpenEditor').onclick=()=>{if(!Auth.isOwner())return;modal.classList.remove('hidden');selectEdit(editId||CardDB.cards[0].id)};$('#btnCloseEditor').onclick=()=>modal.classList.add('hidden');
$('#btnSaveUnit').onclick=e=>{e.preventDefault();const c=CardDB.byId(editId);if(!c)return;for(const [key,,type] of fields){const input=form.elements[key];if(!input)continue;const v=input.value;if(type==='number'){if(v!==''&&!Number.isNaN(Number(v)))c[key]=Number(v)}else if(v!=='')c[key]=v}CardDB.save();renderEditorList();renderCollection();renderDeck()};
$('#btnRestoreDefaults').onclick=()=>{if(confirm('Reset semua override kartu di browser ini?')){CardDB.reset();selectEdit(CardDB.cards[0].id);renderCollection();renderDeck()}};
$('#btnResetCards').onclick=$('#btnRestoreDefaults').onclick;
$('#btnExportCards').onclick=()=>{const blob=new Blob([JSON.stringify(CardDB.cards,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='game-arena-cards.json';a.click();URL.revokeObjectURL(a.href)};

if(Auth.session())enterApp();
})();
