(()=>{
const cache=new Map();
const rarity={common:['#66758b','#26344a'],rare:['#3b82f6','#183a67'],epic:['#a855f7','#4b176d'],legendary:['#f59e0b','#743f08']};
function svgCard(c){const r=rarity[c.rarity]||rarity.common;const bg=`<svg xmlns="http://www.w3.org/2000/svg" width="240" height="300" viewBox="0 0 240 300"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${r[0]}"/><stop offset="1" stop-color="${r[1]}"/></linearGradient><radialGradient id="h"><stop stop-color="#fff" stop-opacity=".32"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient><filter id="s"><feDropShadow dx="0" dy="10" stdDeviation="10" flood-opacity=".55"/></filter></defs><rect width="240" height="300" rx="28" fill="#08111f"/><rect x="7" y="7" width="226" height="286" rx="24" fill="url(#g)" stroke="#fff" stroke-opacity=".45" stroke-width="3"/><ellipse cx="120" cy="112" rx="102" ry="92" fill="url(#h)"/><ellipse cx="120" cy="205" rx="72" ry="20" fill="#000" opacity=".28"/><text x="120" y="175" text-anchor="middle" font-size="105" font-family="Apple Color Emoji,Segoe UI Emoji,sans-serif" filter="url(#s)">${c.emoji}</text><rect x="14" y="226" width="212" height="56" rx="14" fill="#07101d" opacity=".86"/><text x="120" y="250" text-anchor="middle" fill="#fff" font-weight="800" font-size="18" font-family="Arial">${String(c.name).replace(/&/g,'&amp;')}</text><text x="120" y="272" text-anchor="middle" fill="#d8e6ff" font-size="13" font-family="Arial">${c.type.toUpperCase()} • ${c.rarity.toUpperCase()}</text></svg>`;return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(bg)}
function art(c){if(!c)return '';if(!cache.has(c.id))cache.set(c.id,svgCard(c));return cache.get(c.id)}
function enhance(){document.querySelectorAll('.collection-card[data-id]').forEach(el=>{const c=CardDB.byId(el.dataset.id);if(!c)return;el.style.backgroundImage=`linear-gradient(rgba(5,10,20,.08),rgba(5,10,20,.82)),url("${art(c)}")`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';const em=el.querySelector('.emoji');if(em)em.style.opacity='0'});document.querySelectorAll('#hand .card').forEach(el=>{const n=el.querySelector('.name')?.textContent;const c=CardDB.cards.find(x=>x.name===n);if(c){el.style.backgroundImage=`linear-gradient(rgba(0,0,0,.05),rgba(0,0,0,.76)),url("${art(c)}")`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';const em=el.querySelector('.emoji');if(em)em.style.opacity='0'}})}
new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',enhance);
// Canvas: replace emoji glyphs with generated card portraits for a more dimensional look.
const originalFillText=CanvasRenderingContext2D.prototype.fillText;const imgs=new Map();
function imgFor(c){if(!imgs.has(c.id)){const i=new Image();i.src=art(c);imgs.set(c.id,i)}return imgs.get(c.id)}
CanvasRenderingContext2D.prototype.fillText=function(text,x,y,max){if(this.canvas?.id==='game'){const c=CardDB?.cards?.find(v=>v.emoji===text);if(c){const im=imgFor(c);if(im.complete&&im.naturalWidth){const s=34;this.save();this.shadowColor='rgba(0,0,0,.5)';this.shadowBlur=6;this.drawImage(im,0,0,240,220,x-s/2,y-s/2,s,s);this.restore();return}}}return originalFillText.call(this,text,x,y,max)};
window.ArtEngine={art,refresh:enhance};
})();