(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=canvas.width,H=canvas.height,riverY=H/2,bridgeX=[W*.3,W*.7];
let running=false,paused=false,last=performance.now(),timeLeft=180,playerEnergy=5,enemyEnergy=5,playerScore=0,enemyScore=0;
let selected=null,units=[],projectiles=[],effects=[],zones=[],buildings=[],towers=[],playerDeck=[],enemyDeck=[],aiTimer=1.2,resultSent=false;
const handEl=document.getElementById('hand');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function arena(){const p=Auth.getProgress?.();return GameConfig.arenas.find(a=>a.id===p?.selectedArena)||GameConfig.arenas[0]}
function makeTowers(){return[
{id:'pL',team:'p',x:98,y:H-115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:.85,cd:0,king:false},{id:'pR',team:'p',x:W-98,y:H-115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:.85,cd:0,king:false},{id:'pK',team:'p',x:W/2,y:H-52,hp:4200,maxHp:4200,r:30,damage:120,range:135,atk:.8,cd:0,king:true},
{id:'eL',team:'e',x:98,y:115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:.85,cd:0,king:false},{id:'eR',team:'e',x:W-98,y:115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:.85,cd:0,king:false},{id:'eK',team:'e',x:W/2,y:52,hp:4200,maxHp:4200,r:30,damage:120,range:135,atk:.8,cd:0,king:true}]}
function pickEnemyDeck(){return [...CardDB.cards].sort(()=>Math.random()-.5).slice(0,8).map(x=>x.id)}
function levelScale(id){const p=Auth.getProgress?.();const lv=Math.max(1,p?.levels?.[id]||1);return 1+(lv-1)*.08}
function unitFrom(def,team,x,y,scale=1){return{uid:uid(),team,x,y,spawnY:y,hp:(def.hp||1)*scale,maxHp:(def.hp||1)*scale,damage:(def.damage||0)*scale,speed:def.speed||0,range:def.range||20,attackSpeed:def.attackSpeed||1,cd:Math.random()*.2,r:def.radius||10,target:def.target||'any',projectile:!!def.projectile,splash:def.splash||0,flying:!!def.flying,healAura:def.healAura||0,slow:def.slow||0,shield:def.shield||0,color:def.color||'#fff',emoji:def.emoji||'?',name:def.name||def.id,type:'troop',stun:0,freeze:0,anim:Math.random()*6.28,spawnEvery:def.spawnEvery||0,spawnCd:def.spawnEvery||0,spawnId:def.spawnId,spawnCount:def.spawnCount||1,reviveOnce:def.reviveOnce||false,revived:false}}
function deployTroop(def,team,x,y){const scale=team==='p'?levelScale(def.id):1+Math.random()*.12;for(let i=0;i<(def.count||1);i++){const ang=i/Math.max(1,def.count)*Math.PI*2;units.push(unitFrom(def,team,x+Math.cos(ang)*12,y+Math.sin(ang)*12,scale))}burst(x,y,def.color||'#fff',10)}
function deployBuilding(def,team,x,y){buildings.push({uid:uid(),team,x,y,hp:def.hp,maxHp:def.hp,r:def.radius||18,damage:def.damage||0,range:def.range||0,atk:def.attackSpeed||1,cd:.3,life:def.duration||30,maxLife:def.duration||30,target:def.target||'any',spawnEvery:def.spawnEvery||0,spawnCd:def.spawnEvery||0,spawnId:def.spawnId,spawnCount:def.spawnCount||1,emoji:def.emoji,color:def.color||'#aaa',type:'building'});burst(x,y,def.color||'#fff',14)}
function castSpell(def,team,x,y){effects.push({type:'spell',x,y,life:.65,maxLife:.65,r:def.radius||70,color:def.color||'#fff',emoji:def.emoji});
 const enemy=team==='p'?'e':'p';
 for(const u of units){if(dist(u,{x,y})<=def.radius){if(def.heal&&u.team===team)u.hp=Math.min(u.maxHp,u.hp+def.heal);if(u.team===enemy){if(def.damage)damage(u,def.damage);if(def.freeze)u.freeze=Math.max(u.freeze,def.freeze);if(def.stun)u.stun=Math.max(u.stun,def.stun)}}}
 for(const b of buildings){if(b.team===enemy&&dist(b,{x,y})<=def.radius&&def.damage)damage(b,def.damage*.8)}
 for(const t of towers){if(t.team===enemy&&t.hp>0&&dist(t,{x,y})<=def.radius&&def.damage)damage(t,def.damage*.65)}
 if(def.damagePerSecond&&def.duration)zones.push({team,x,y,r:def.radius,life:def.duration,dps:def.damagePerSecond,color:def.color,tick:0});
}
function burst(x,y,color,count=8){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*80;effects.push({type:'particle',x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.35,maxLife:.7,color})}}
function start(deck){running=true;paused=false;resultSent=false;units=[];projectiles=[];effects=[];zones=[];buildings=[];towers=makeTowers();timeLeft=GameConfig.battle.durationSeconds;playerEnergy=GameConfig.battle.startEnergy;enemyEnergy=GameConfig.battle.startEnergy;playerScore=enemyScore=0;selected=null;playerDeck=(deck&&deck.length?deck:Auth.getProgress().deck).slice(0,8);enemyDeck=pickEnemyDeck();aiTimer=1;renderHand();last=performance.now()}
function renderHand(){handEl.innerHTML='';playerDeck.slice(0,4).forEach(id=>{const d=CardDB.byId(id);if(!d)return;const el=document.createElement('div');el.className='card'+(selected===id?' selected':'');el.innerHTML=`<div class="cost">${d.cost}</div><div class="emoji">${d.emoji}</div><div class="name">${d.name}</div>`;el.onclick=()=>{selected=id;renderHand()};handEl.appendChild(el)})}
function cycle(id){const i=playerDeck.indexOf(id);if(i>=0){const [x]=playerDeck.splice(i,1);playerDeck.push(x)}selected=null;renderHand()}
function pos(ev){const r=canvas.getBoundingClientRect(),p=ev.touches?ev.touches[0]:ev;return{x:(p.clientX-r.left)/r.width*W,y:(p.clientY-r.top)/r.height*H}}
function tryDeploy(ev){if(!running||paused||!selected)return;const p=pos(ev),d=CardDB.byId(selected);if(!d||playerEnergy<d.cost)return;if(d.type!=='spell'&&p.y<riverY+18)return;playerEnergy-=d.cost;if(d.type==='troop')deployTroop(d,'p',clamp(p.x,25,W-25),clamp(p.y,riverY+35,H-90));else if(d.type==='building')deployBuilding(d,'p',clamp(p.x,32,W-32),clamp(p.y,riverY+38,H-105));else castSpell(d,'p',p.x,p.y);cycle(selected)}canvas.addEventListener('click',tryDeploy);
function allTargets(u){let arr=[...units.filter(v=>v.team!==u.team&&v.hp>0),...buildings.filter(v=>v.team!==u.team&&v.hp>0),...towers.filter(v=>v.team!==u.team&&v.hp>0)];if(u.target==='ground')arr=arr.filter(v=>!v.flying);if(u.target==='buildings')arr=arr.filter(v=>v.type==='building'||v.id);return arr}
function nearest(u){let best=null,bd=1e9;for(const t of allTargets(u)){const d=dist(u,t);if(d<bd){bd=d;best=t}}return best}
function bridgeTarget(u,t){let tx=t.x,ty=t.y;if(!u.flying&&((u.team==='p'&&u.y>riverY&&ty<riverY)||(u.team==='e'&&u.y<riverY&&ty>riverY))){const bx=bridgeX.reduce((a,b)=>Math.abs(u.x-a)<Math.abs(u.x-b)?a:b);if(Math.abs(u.y-riverY)>20){tx=bx;ty=u.team==='p'?riverY+8:riverY-8}}return{x:tx,y:ty}}
function damage(t,amount,att){if(!t||t.hp<=0)return;let left=amount;if(t.shield>0){const use=Math.min(t.shield,left);t.shield-=use;left-=use}t.hp-=left;if(att?.splash){for(const o of units){if(o.team!==att.team&&o!==t&&o.hp>0&&dist(o,t)<att.splash)o.hp-=left*.45}}burst(t.x,t.y,att?.color||'#ffd56b',4)}
function attack(att,t){if(att.projectile)projectiles.push({x:att.x,y:att.y,target:t,team:att.team,damage:att.damage,splash:att.splash||0,color:att.color,speed:300,life:2.4});else damage(t,att.damage,att)}
function updateUnit(u,dt){if(u.hp<=0)return;u.anim+=dt*(u.speed?8:3);u.stun=Math.max(0,u.stun-dt);u.freeze=Math.max(0,u.freeze-dt);if(u.healAura)for(const a of units)if(a.team===u.team&&a!==u&&a.hp>0&&dist(a,u)<60)a.hp=Math.min(a.maxHp,a.hp+u.healAura*dt);if(u.spawnEvery){u.spawnCd-=dt;if(u.spawnCd<=0){u.spawnCd=u.spawnEvery;const d=CardDB.byId(u.spawnId);if(d)for(let i=0;i<u.spawnCount;i++)units.push(unitFrom(d,u.team,u.x+(Math.random()-.5)*18,u.y+(Math.random()-.5)*18,1))}}if(u.stun>0||u.freeze>0)return;u.cd-=dt;const t=nearest(u);if(!t)return;const d=dist(u,t);if(d<=u.range+(t.r||8)){if(u.cd<=0){u.cd=u.attackSpeed;attack(u,t)}}else{const q=bridgeTarget(u,t),dx=q.x-u.x,dy=q.y-u.y,len=Math.hypot(dx,dy)||1;const slow=u.freeze>0?.35:1;u.x+=dx/len*u.speed*slow*dt;u.y+=dy/len*u.speed*slow*dt}}
function updateBuilding(b,dt){b.life-=dt;b.cd-=dt;if(b.spawnEvery){b.spawnCd-=dt;if(b.spawnCd<=0){b.spawnCd=b.spawnEvery;const d=CardDB.byId(b.spawnId);if(d)deployTroop(d,b.team,b.x,b.y+(b.team==='p'?-18:18))}}if(b.damage<=0||b.cd>0)return;const enemies=units.filter(u=>u.team!==b.team&&u.hp>0&&dist(u,b)<=b.range);if(enemies.length){b.cd=b.atk;const t=enemies.sort((a,c)=>dist(a,b)-dist(c,b))[0];projectiles.push({x:b.x,y:b.y,target:t,team:b.team,damage:b.damage,splash:0,color:b.color,speed:320,life:2})}}
function updateProjectiles(dt){for(const p of projectiles){p.life-=dt;if(!p.target||p.target.hp<=0)continue;const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy)||1;if(d<12){damage(p.target,p.damage,p);p.life=0}else{p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt}}projectiles=projectiles.filter(p=>p.life>0)}
function updateTowers(dt){for(const t of towers){if(t.hp<=0)continue;t.cd-=dt;const e=units.filter(u=>u.team!==t.team&&u.hp>0&&dist(u,t)<=t.range);if(e.length&&t.cd<=0){t.cd=t.atk;const target=e.sort((a,b)=>dist(a,t)-dist(b,t))[0];projectiles.push({x:t.x,y:t.y,target,team:t.team,damage:t.damage,splash:0,color:'#fff',speed:330,life:2})}}}
function updateZones(dt){for(const z of zones){z.life-=dt;z.tick-=dt;if(z.tick<=0){z.tick=.5;for(const u of units)if(u.team!==z.team&&dist(u,z)<=z.r)damage(u,z.dps*.5)}}zones=zones.filter(z=>z.life>0)}
function deaths(){for(const u of units){if(u.hp<=0&&!u.dead){u.dead=true;burst(u.x,u.y,u.color,10);if(u.reviveOnce&&!u.revived){u.hp=u.maxHp*.55;u.revived=true;u.dead=false;burst(u.x,u.y,'#ffb74d',18)}}}units=units.filter(u=>u.hp>0);for(const b of buildings)if(b.hp<=0||b.life<=0)burst(b.x,b.y,b.color,8);buildings=buildings.filter(b=>b.hp>0&&b.life>0);for(const t of towers){if(t.hp<=0&&!t.dead){t.dead=true;burst(t.x,t.y,'#ffd36d',22);if(t.team==='e')playerScore+=t.king?3:1;else enemyScore+=t.king?3:1}}}
function ai(dt){aiTimer-=dt;if(aiTimer>0)return;aiTimer=.65+Math.random()*1.2;const opts=enemyDeck.map(id=>CardDB.byId(id)).filter(d=>d&&d.cost<=enemyEnergy);if(!opts.length)return;const d=opts[Math.floor(Math.random()*opts.length)],x=55+Math.random()*(W-110),y=70+Math.random()*210;enemyEnergy-=d.cost;if(d.type==='troop')deployTroop(d,'e',x,y);else if(d.type==='building')deployBuilding(d,'e',x,85+Math.random()*180);else castSpell(d,'e',55+Math.random()*(W-110),riverY+70+Math.random()*250);const i=enemyDeck.indexOf(d.id);enemyDeck.push(...enemyDeck.splice(i,1))}
function finish(){if(resultSent)return;resultSent=true;running=false;const win=playerScore>enemyScore||(playerScore===enemyScore&&towerHp('e')<towerHp('p'));window.dispatchEvent(new CustomEvent('arena:result',{detail:{win,playerScore,enemyScore}}))}
function towerHp(team){return towers.filter(t=>t.team===team).reduce((s,t)=>s+Math.max(0,t.hp),0)}
function update(dt){const cfg=GameConfig.battle,rate=timeLeft<60?cfg.doubleEnergyPerSecond:cfg.normalEnergyPerSecond;playerEnergy=Math.min(cfg.maxEnergy,playerEnergy+dt*rate);enemyEnergy=Math.min(cfg.maxEnergy,enemyEnergy+dt*rate);timeLeft-=dt;if(timeLeft<=0){timeLeft=0;finish()}for(const u of units)updateUnit(u,dt);for(const b of buildings)updateBuilding(b,dt);updateTowers(dt);updateProjectiles(dt);updateZones(dt);for(const e of effects){e.life-=dt;if(e.type==='particle'){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vy+=70*dt}}effects=effects.filter(e=>e.life>0);deaths();if(towers.find(t=>t.id==='eK')?.hp<=0||towers.find(t=>t.id==='pK')?.hp<=0)finish();ai(dt)}
function hpBar(x,y,w,hp,max,shield=0){ctx.fillStyle='rgba(0,0,0,.48)';ctx.fillRect(x-w/2,y,w,4);ctx.fillStyle=hp/max>.5?'#62e36f':hp/max>.25?'#ffd15d':'#ff5e65';ctx.fillRect(x-w/2,y,w*(Math.max(0,hp)/max),4);if(shield>0){ctx.fillStyle='#7cc8ff';ctx.fillRect(x-w/2,y-3,Math.min(w,w*shield/max),2)}}
function drawArena(){const a=arena();ctx.clearRect(0,0,W,H);ctx.fillStyle=a.ground;ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=40)for(let x=(y/40)%2*20;x<W;x+=40){ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(x,y,20,20)}ctx.fillStyle=a.river;ctx.fillRect(0,riverY-20,W,40);ctx.fillStyle=a.bridge;for(const bx of bridgeX)ctx.fillRect(bx-35,riverY-24,70,48)}
function drawTowers(){for(const t of towers){if(t.hp<=0)continue;const pulse=1+Math.sin(performance.now()/220+t.x)*.03;ctx.save();ctx.translate(t.x,t.y);ctx.scale(pulse,pulse);ctx.fillStyle=t.team==='p'?'#2e79dc':'#d94b58';ctx.beginPath();ctx.arc(0,0,t.r,0,Math.PI*2);ctx.fill();ctx.font=t.king?'24px sans-serif':'20px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.king?'👑':'🏰',0,0);ctx.restore();hpBar(t.x,t.y-t.r-10,t.r*2,t.hp,t.maxHp)}}
function drawBuildings(){for(const b of buildings){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.sin(performance.now()/350+b.x)*.03);ctx.fillStyle=b.color;ctx.beginPath();ctx.roundRect(-b.r,-b.r,b.r*2,b.r*2,6);ctx.fill();ctx.font=`${b.r+7}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.emoji,0,0);ctx.restore();hpBar(b.x,b.y-b.r-10,b.r*2,b.hp,b.maxHp)}}
function drawUnits(){for(const u of units){const bob=Math.sin(u.anim)*1.8,lean=Math.sin(u.anim*.7)*.08;ctx.save();ctx.translate(u.x,u.y+bob);ctx.rotate(lean);ctx.fillStyle=u.team==='p'?'rgba(55,142,255,.30)':'rgba(255,78,93,.30)';ctx.beginPath();ctx.arc(0,0,u.r+5,0,Math.PI*2);ctx.fill();ctx.fillStyle=u.color;ctx.beginPath();ctx.arc(0,0,u.r,0,Math.PI*2);ctx.fill();ctx.font=`${Math.max(12,u.r+8)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(u.emoji,0,0);if(u.freeze>0){ctx.strokeStyle='#b6ecff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,u.r+3,0,Math.PI*2);ctx.stroke()}ctx.restore();hpBar(u.x,u.y-u.r-10,u.r*2.5,u.hp,u.maxHp,u.shield)}}
function drawProjectiles(){for(const p of projectiles){ctx.fillStyle=p.color||'#fff';ctx.shadowColor=p.color||'#fff';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}}
function drawEffects(){for(const z of zones){ctx.globalAlpha=.16;ctx.fillStyle=z.color;ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}for(const e of effects){const a=Math.max(0,e.life/(e.maxLife||1));ctx.globalAlpha=a;if(e.type==='particle'){ctx.fillStyle=e.color;ctx.fillRect(e.x-2,e.y-2,4,4)}else{ctx.strokeStyle=e.color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,(e.r||70)*(1-a*.25),0,Math.PI*2);ctx.stroke();ctx.font='32px sans-serif';ctx.textAlign='center';ctx.fillText(e.emoji||'✨',e.x,e.y)}ctx.globalAlpha=1}}
function draw(){drawArena();drawTowers();drawBuildings();drawUnits();drawProjectiles();drawEffects();document.getElementById('energyText').textContent=`${playerEnergy.toFixed(1)} / ${GameConfig.battle.maxEnergy}`;document.getElementById('energyFill').style.width=(playerEnergy/GameConfig.battle.maxEnergy*100)+'%';document.getElementById('playerScore').textContent=playerScore;document.getElementById('enemyScore').textContent=enemyScore;const s=Math.ceil(timeLeft),m=Math.floor(s/60),ss=String(Math.max(0,s%60)).padStart(2,'0');document.getElementById('timer').textContent=`${m}:${ss}`}
function loop(now){const dt=Math.min(.034,(now-last)/1000);last=now;if(running&&!paused)update(dt);if(!document.getElementById('screenBattle').classList.contains('active')){}draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
document.getElementById('btnPause').onclick=()=>{paused=!paused;document.getElementById('btnPause').textContent=paused?'▶':'⏸'};document.getElementById('btnReset').onclick=()=>start(Auth.getProgress().deck);
window.ArenaGame={start,stop(){running=false},isRunning:()=>running};
})();
