(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=canvas.width,H=canvas.height,riverY=H/2,bridgeX=[W*.3,W*.7];
let selected=null,paused=false,last=performance.now(),timeLeft=180,playerEnergy=5,enemyEnergy=5,playerScore=0,enemyScore=0;
let units=[],projectiles=[],effects=[],towers=[];
let playerDeck=[],enemyDeck=[];
const handEl=document.getElementById('hand');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)); const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function makeTowers(){return [
 {id:'pL',team:'p',x:98,y:H-115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:0.85,cd:0,king:false},
 {id:'pR',team:'p',x:W-98,y:H-115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:0.85,cd:0,king:false},
 {id:'pK',team:'p',x:W/2,y:H-52,hp:4200,maxHp:4200,r:30,damage:120,range:135,atk:0.8,cd:0,king:true},
 {id:'eL',team:'e',x:98,y:115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:0.85,cd:0,king:false},
 {id:'eR',team:'e',x:W-98,y:115,hp:2600,maxHp:2600,r:25,damage:95,range:122,atk:0.85,cd:0,king:false},
 {id:'eK',team:'e',x:W/2,y:52,hp:4200,maxHp:4200,r:30,damage:120,range:135,atk:0.8,cd:0,king:true}
]}
function pickDeck(){const ids=UnitDB.units.map(u=>u.id),sh=[...ids].sort(()=>Math.random()-.5);return sh.slice(0,8)}
function reset(){units=[];projectiles=[];effects=[];towers=makeTowers();timeLeft=180;playerEnergy=5;enemyEnergy=5;playerScore=enemyScore=0;playerDeck=pickDeck();enemyDeck=pickDeck();selected=null;renderHand();updateDeckInfo();paused=false;document.getElementById('btnPause').textContent='⏸ Pause'}
function unitFrom(def,team,x,y){return {uid:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36),team,x,y,hp:def.hp,maxHp:def.hp,damage:def.damage,speed:def.speed,range:def.range,attackSpeed:def.attackSpeed,cd:Math.random()*.3,r:def.radius||9,target:def.target||'any',projectile:!!def.projectile,splash:def.splash||0,flying:!!def.flying,healAura:def.healAura||0,color:def.color||'#fff',emoji:def.emoji,name:def.name}}
function deploy(def,team,x,y){for(let i=0;i<(def.count||1);i++){const ang=(i/(def.count||1))*Math.PI*2;units.push(unitFrom(def,team,x+Math.cos(ang)*12,y+Math.sin(ang)*12))}}
function renderHand(){handEl.innerHTML='';playerDeck.slice(0,4).forEach(id=>{const d=UnitDB.byId(id);if(!d)return;const el=document.createElement('div');el.className='card'+(selected===id?' selected':'');el.innerHTML=`<div class="cost">${d.cost}</div><div class="emoji">${d.emoji}</div><div class="name">${d.name}</div>`;el.onclick=()=>{selected=id;renderHand()};handEl.appendChild(el)})}
function cycleCard(id){const i=playerDeck.indexOf(id);if(i>=0){const [x]=playerDeck.splice(i,1);playerDeck.push(x)}selected=null;renderHand();updateDeckInfo()}
function canvasPos(ev){const r=canvas.getBoundingClientRect();const p=ev.touches?ev.touches[0]:ev;return {x:(p.clientX-r.left)/r.width*W,y:(p.clientY-r.top)/r.height*H}}
function tryDeploy(ev){if(paused||!selected)return;const p=canvasPos(ev);if(p.y<riverY+18)return;const d=UnitDB.byId(selected);if(!d||playerEnergy<d.cost)return;playerEnergy-=d.cost;deploy(d,'p',clamp(p.x,28,W-28),clamp(p.y,riverY+35,H-90));cycleCard(selected)}
canvas.addEventListener('click',tryDeploy);
function bridgeAdjustedTarget(u,t){let tx=t.x,ty=t.y;if(!u.flying && ((u.team==='p'&&u.y>riverY&&ty<riverY)||(u.team==='e'&&u.y<riverY&&ty>riverY))){const bx=bridgeX.reduce((a,b)=>Math.abs(u.x-a)<Math.abs(u.x-b)?a:b);if(Math.abs(u.y-riverY)>20){tx=bx;ty=u.team==='p'?riverY+8:riverY-8}}return {x:tx,y:ty}}
function validTargets(u){let arr=[...units.filter(v=>v.team!==u.team&&v.hp>0)];if(u.target==='ground')arr=arr.filter(v=>!v.flying);if(u.target==='buildings')arr=[];arr.push(...towers.filter(t=>t.team!==u.team&&t.hp>0));return arr}
function nearest(u){const arr=validTargets(u);let best=null,bd=1e9;for(const t of arr){const d=dist(u,t);if(d<bd){bd=d;best=t}}return best}
function damageTarget(att,t){if(!t||t.hp<=0)return;t.hp-=att.damage;if(att.splash){for(const other of units){if(other.team!==att.team&&other!==t&&other.hp>0&&dist(t,other)<att.splash)other.hp-=att.damage*.45}}effects.push({x:t.x,y:t.y,life:.22})}
function updateUnit(u,dt){if(u.hp<=0)return;if(u.healAura){for(const a of units){if(a.team===u.team&&a!==u&&a.hp>0&&dist(a,u)<58)a.hp=Math.min(a.maxHp,a.hp+u.healAura*dt)}}u.cd-=dt;const t=nearest(u);if(!t)return;const d=dist(u,t);if(d<=u.range+(t.r||8)){if(u.cd<=0){u.cd=u.attackSpeed;if(u.projectile)projectiles.push({x:u.x,y:u.y,target:t,team:u.team,damage:u.damage,splash:u.splash,speed:280,life:2.5});else damageTarget(u,t)}}else{const q=bridgeAdjustedTarget(u,t),dx=q.x-u.x,dy=q.y-u.y,len=Math.hypot(dx,dy)||1;u.x+=dx/len*u.speed*dt;u.y+=dy/len*u.speed*dt}}
function updateProjectiles(dt){for(const p of projectiles){p.life-=dt;if(!p.target||p.target.hp<=0)continue;const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy)||1;if(d<12){damageTarget(p,p.target);p.life=0}else{p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt}}projectiles=projectiles.filter(p=>p.life>0)}
function updateTowers(dt){for(const t of towers){if(t.hp<=0)continue;t.cd-=dt;const enemies=units.filter(u=>u.team!==t.team&&u.hp>0&&dist(u,t)<=t.range);if(enemies.length&&t.cd<=0){t.cd=t.atk;const target=enemies.sort((a,b)=>dist(a,t)-dist(b,t))[0];projectiles.push({x:t.x,y:t.y,target,team:t.team,damage:t.damage,splash:0,speed:320,life:2})}}}
function checkDeaths(){for(const t of towers){if(t.hp<=0&&!t.dead){t.dead=true;if(t.team==='e')playerScore+=t.king?3:1;else enemyScore+=t.king?3:1}}units=units.filter(u=>u.hp>0)}
let aiTimer=1.2;function ai(dt){aiTimer-=dt;if(aiTimer>0)return;aiTimer=.7+Math.random()*1.4;const opts=enemyDeck.map(id=>UnitDB.byId(id)).filter(d=>d&&d.cost<=enemyEnergy);if(!opts.length)return;const d=opts[Math.floor(Math.random()*opts.length)];enemyEnergy-=d.cost;deploy(d,'e',60+Math.random()*(W-120),75+Math.random()*190);const i=enemyDeck.indexOf(d.id);enemyDeck.push(...enemyDeck.splice(i,1))}
function update(dt){playerEnergy=Math.min(10,playerEnergy+dt*(timeLeft<60?1.25:.72));enemyEnergy=Math.min(10,enemyEnergy+dt*(timeLeft<60?1.25:.72));timeLeft-=dt;if(timeLeft<=0){timeLeft=0;paused=true}for(const u of units)updateUnit(u,dt);updateTowers(dt);updateProjectiles(dt);for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0);checkDeaths();ai(dt)}
function hpBar(x,y,w,hp,max){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(x-w/2,y,w,4);ctx.fillStyle=hp/max>.5?'#62e36f':hp/max>.25?'#ffd15d':'#ff5e65';ctx.fillRect(x-w/2,y,w*(Math.max(0,hp)/max),4)}
function drawArena(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#5f934f';ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=40){for(let x=(y/40)%2*20;x<W;x+=40){ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(x,y,20,20)}}ctx.fillStyle='#57a6d8';ctx.fillRect(0,riverY-20,W,40);ctx.fillStyle='#b9935f';for(const bx of bridgeX)ctx.fillRect(bx-35,riverY-24,70,48);ctx.strokeStyle='rgba(255,255,255,.22)';ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(0,riverY);ctx.lineTo(W,riverY);ctx.stroke();ctx.setLineDash([])}
function drawTowers(){for(const t of towers){if(t.hp<=0)continue;ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle=t.team==='p'?'#2e79dc':'#d94b58';ctx.beginPath();ctx.arc(0,0,t.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=t.king?'24px sans-serif':'20px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.king?'👑':'🏰',0,1);ctx.restore();hpBar(t.x,t.y-t.r-10,t.r*2,t.hp,t.maxHp)}}
function drawUnits(){for(const u of units){ctx.save();ctx.translate(u.x,u.y);ctx.fillStyle=u.team==='p'?'rgba(55,142,255,.30)':'rgba(255,78,93,.30)';ctx.beginPath();ctx.arc(0,0,u.r+5,0,Math.PI*2);ctx.fill();ctx.fillStyle=u.color;ctx.beginPath();ctx.arc(0,0,u.r,0,Math.PI*2);ctx.fill();ctx.font=`${Math.max(12,u.r+8)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(u.emoji,0,0);ctx.restore();hpBar(u.x,u.y-u.r-9,u.r*2.4,u.hp,u.maxHp)}}
function drawProjectiles(){for(const p of projectiles){ctx.fillStyle=p.team==='p'?'#d9ecff':'#ffd9dd';ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,Math.PI*2);ctx.fill()}}
function drawEffects(){for(const e of effects){ctx.strokeStyle=`rgba(255,230,130,${e.life/.22})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,(.22-e.life)*45,0,Math.PI*2);ctx.stroke()}}
function draw(){drawArena();drawTowers();drawUnits();drawProjectiles();drawEffects();document.getElementById('energyText').textContent=`${playerEnergy.toFixed(1)} / 10`;document.getElementById('energyFill').style.width=(playerEnergy*10)+'%';document.getElementById('playerScore').textContent=playerScore;document.getElementById('enemyScore').textContent=enemyScore;const s=Math.ceil(timeLeft),m=Math.floor(s/60),ss=String(s%60).padStart(2,'0');document.getElementById('timer').textContent=`${m}:${ss}`}
function loop(now){const dt=Math.min(.034,(now-last)/1000);last=now;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
function updateDeckInfo(){document.getElementById('deckInfo').innerHTML=playerDeck.map(id=>{const d=UnitDB.byId(id);return d?`<span class="chip">${d.emoji} ${d.name}</span>`:''}).join('')}
document.getElementById('btnPause').onclick=()=>{paused=!paused;document.getElementById('btnPause').textContent=paused?'▶ Lanjut':'⏸ Pause'};document.getElementById('btnReset').onclick=reset;document.getElementById('btnRandomDeck').onclick=()=>{playerDeck=pickDeck();selected=null;renderHand();updateDeckInfo()};

// Editor
const modal=document.getElementById('editorModal'),list=document.getElementById('unitList'),form=document.getElementById('unitForm');let editId=null;
const fields=[['name','Nama','text'],['emoji','Emoji','text'],['cost','Cost Energi','number'],['hp','HP','number'],['damage','Damage','number'],['speed','Movement Speed','number'],['range','Attack Range','number'],['attackSpeed','Attack Cooldown (detik)','number'],['count','Jumlah Spawn','number'],['radius','Ukuran Unit','number'],['splash','Splash Radius','number'],['healAura','Heal / detik','number'],['color','Warna','color']];
function renderUnitList(){list.innerHTML='';UnitDB.units.forEach(u=>{const b=document.createElement('button');b.type='button';b.className='unit-row'+(editId===u.id?' active':'');b.innerHTML=`<span>${u.emoji}</span><span>${u.name}<br><small>${u.damage} DMG • ${u.hp} HP</small></span>`;b.onclick=()=>selectEdit(u.id);list.appendChild(b)})}
function selectEdit(id){editId=id;const u=UnitDB.byId(id);form.innerHTML='';for(const [key,label,type] of fields){const div=document.createElement('div');div.className='field';div.innerHTML=`<label>${label}</label><input name="${key}" type="${type}" step="any" value="${u[key]??(type==='color'?'#ffffff':0)}">`;form.appendChild(div)}const div=document.createElement('div');div.className='field full';div.innerHTML=`<label>Target</label><select name="target"><option value="any">Semua</option><option value="ground">Ground saja</option><option value="buildings">Building saja</option></select>`;form.appendChild(div);form.elements.target.value=u.target||'any';renderUnitList()}
function openEditor(){modal.classList.remove('hidden');selectEdit(editId||UnitDB.units[0].id)}
document.getElementById('btnEditor').onclick=openEditor;document.getElementById('btnCloseEditor').onclick=()=>modal.classList.add('hidden');
document.getElementById('btnSaveUnit').onclick=e=>{e.preventDefault();const u=UnitDB.byId(editId);if(!u)return;for(const [key,,type] of fields){const v=form.elements[key].value;u[key]=type==='number'?Number(v):v}u.target=form.elements.target.value;UnitDB.save();renderUnitList();renderHand();updateDeckInfo()};
document.getElementById('btnRestoreDefaults').onclick=()=>{if(!confirm('Kembalikan semua unit ke nilai default?'))return;UnitDB.reset();editId=UnitDB.units[0].id;selectEdit(editId);reset()};
document.getElementById('btnExport').onclick=()=>{const blob=new Blob([JSON.stringify(UnitDB.units,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='arena-tactics-units.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x))throw Error('Format harus array');UnitDB.units=x;UnitDB.save();editId=x[0]?.id||null;if(editId)selectEdit(editId);reset()}catch(err){alert('JSON tidak valid: '+err.message)}e.target.value=''};
reset();requestAnimationFrame(loop);
})();
